image: node:20.2.0

pages:
  cache:
    paths:
      - node_modules/
    key:
      files:
        - yarn.lock
  before_script:
    - export NODE_OPTIONS=--openssl-legacy-provider
    - export NODE_OPTIONS=--max-old-space-size=4096
    - yarn install
  script:
    - yarn docs:build
  artifacts:
    paths:
      - public
  only:
    - main